myshare/link_posts/routes.py
from flask import (render_template, url_for, flash,
                   request, abort, redirect, Blueprint)
from flask_login import current_user, login_required
from myshare import db
from myshare.models import Link
from myshare.link_posts.forms import PostForm


link_posts = Blueprint('link_posts', __name__)

#Route where users create new posts
@link_posts.route("/post/new", methods=["GET","POST"])
@login_required
def new_post():
    form = PostForm()
    if request.method == "POST":
        title = form.title.data
        link = form.link.data
        
        if title and link:
            link_post = Link(title=title, content=link, author=current_user)
            db.session.add(link_post)
            db.session.commit()
            flash("Post has been created succesfully", category="success")
            return redirect(url_for("main.home"))
        else:
            flash("Fill all fields to submit form", category="error")
        
    return render_template("create_post.html", title="Create post",
                           legend="New post:", form=form)


#Route where users can update their posts    
@link_posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    
    link_post = Link.query.get(post_id)
    if link_post.author != current_user:
        abort(403)
    
    form = PostForm()
    if request.method == "POST":
        
        if form.title.data and form.link.data:
            
            link_post.title = form.title.data
            link_post.content = form.link.data
            db.session.commit()
            flash("Your post has been updated succesfully.", category="success")
            return redirect(url_for("link_posts.update_post", post_id=link_post.id))
    
    if request.method == "GET":
        form.title.data = link_post.title
        form.link.data = link_post.content
        
    form.title.data = link_post.title
    form.link.data = link_post.content
        
    return render_template("create_post.html", title="Update post", 
                            legend="Update Post:", link_title=link_post.title,         
                            content=link_post.content, form=form, link=link_post)


#Route to delete posts
@link_posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    link_post = Link.query.get_or_404(post_id)
    if link_post.author != current_user:
        abort(403)
        
    db.session.delete(link_post)
    db.session.commit()
    flash("Your post have been deleted successfully", category="success")
    return redirect(url_for("main.home"))

myshare/main/routes.py
from flask import render_template, request, Blueprint
from myshare.models import Link
from flask_login import login_required

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
@login_required
def home():
    page = request.args.get("page", 1, type=int)
    links = Link.query.order_by(Link.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", links=links)

@main.route("/about")
def about():
    return render_template("about.html", title="About")

myshare/users/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, Blueprint)
from flask_login import (login_user, current_user, logout_user,
                         login_required)
from werkzeug.security import generate_password_hash, check_password_hash
from myshare import db
from myshare.models import User, Link
from myshare.users.forms import (RegistrationForm,
                                 LoginForm, UpdateUserAccount,
                                 RequestResetForm, ResetPasswordForm)
from myshare.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home")) 

@users.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if request.method == "POST":
        email  = form.email.data
        password = form.password.data
        
        user = User.query.filter_by(email=email).first()
        
        if user:
            
            if check_password_hash(user.password, password):
                flash("Login successful!", category="success")
                login_user(user, remember=False)
                next_page = request.args.get("next")
                return redirect(next_page) if next_page else redirect(url_for("main.home"))
            
            else:
                flash("Incorrect password!", category="error") 
        else:
            flash("Email does not exist", category="error")
            
    return render_template("login.html", title="Login", form=form)

@users.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    form = RegistrationForm()
    
    if request.method == "POST":
        email = form.email.data
        user_name = form.username.data
        password = form.password.data
        confirm_password = form.confirm_password.data
        
        # Checking database to make sure no instance of user and email b4 creating a new user, for they are to be unique.
        user = User.query.filter_by(username=user_name).first()
        email_ = User.query.filter_by(email=email).first()
        
        if user:
            flash("That username is taken. Please choose another username", category="error")
        
        elif email_:
            flash("That email is taken. Please choose another email", category="error")
        ##########################################
        # Some validation checks   
        if len(user_name) < 2:
            flash("Your name should be less than 2 letters", category="error")
        elif len(password) < 7:
            flash("Password should not be less than 7 characters", category="error")
        elif password != confirm_password:
            flash("Passwords do not match", category="error")
            
        else:
            new_user = User(email=email, username=user_name, password=generate_password_hash(password, method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            flash(f"Account created successsfully. Welcome {user_name.title()}", category="success")
            return redirect(url_for("users.login"))
            
            
    return render_template("sign-up.html", title="Sign up", form=form)

@users.route("/account", methods=["GET","POST"])
@login_required
def account():
    
    form = UpdateUserAccount()
    
    if request.method == "POST":
        
        if form.email.data != current_user.email or form.username.data != current_user.username:
            
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash("Your profile have been updated successfully", category="success")
            return redirect(url_for("users.account"))
         
        else:
            flash("New data should not match former data", category="error")
            
    if request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template("account.html", image_file=image_file, title="Account",form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    links = Link.query.filter_by(author=user)\
            .order_by(Link.date_posted.desc())\
            .paginate(page=page, per_page=5)
    return render_template("user_posts.html", links=links, user=user)


@users.route("/reset_password", methods=['GET', "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if request.method == "POST":
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            return redirect(url_for('users.login'))
        else:
            flash("User was not found in the database, You can signup first.")
            return redirect(url_for('users.sign_up'))

    return render_template("reset_request.html", title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=['GET', "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token.", category="error")
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    
    if request.method == "POST":
        
        if form.password.data < 7:
            flash("Password should not be less than 7 characters", category="error")
        elif form.password.data != form.confirm_password.data:
            flash("Passwords do not match", category="error")
        else:
            hashed_password = generate_password_hash(form.password.data,  method="sha256")
            user.password = hashed_password
            db.session.commit()
            flash("Your password has been updated", category="success")
            return redirect(url_for("users.login"))
    # elif len(password) < 7:
    #     flash("Password should not be less than 7 characters", category="error")
    # elif password != confirm_password:
    #     flash("Passwords do not match", category="error") 
    # else:
    #     user.password = hashed_password
    #     db.session.commit()
    #     flash("Your password has been updated", category="success")
    #     return redirect(url_for("login"))
    
    return render_template('reset_token.html', title='Reset password', form=form)

myshare/templates/account.html
{% extends "base.html" %} 

{% block title %}Account{% endblock%}

{% block content%}

<div class="account-div">
    <!-- <img class="account-img" src="{{ image_file }}"> -->
    <h2>{{ current_user.username }}</h2>
    <p>{{ current_user.email }}</p>
</div>
<br>
<p id="account-form">Use form below to update user information👇</p>
<br>
<div>
<form class="my-form post-form" method="POST">
    <div class="form-group">
       {{ form.username.label }}
       {{ form.username(type="text", id="title") }}
   </div>
   <div class="form-group">
       {{ form.email.label }}
       {{ form.email }}
   </div>
   <div class="form-group">
       {{ form.submit(type="submit", class="button") }}
   </div>
</form>
</div>



{% endblock %}

myshare/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/my_favicon.ico" rel="icon"/>
    <link href="/static/styles.css" rel="stylesheet">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>MyShare</title>
    {% endif %}

</head>
<body>
    <div class="nav_bar">
        {% if current_user.is_authenticated %}

            <a class="hyper" href="{{ url_for('main.home') }}">Home</a>
            <a class="hyper" href="{{ url_for('users.account') }}">Profile</a>
            <a class="hyper" href="{{ url_for('link_posts.new_post') }}">New post</a>
            <a class="hyper" href="{{ url_for('users.logout') }}">Logout</a>
            
        {% else %}

            <a class="hyper" href="{{ url_for('users.login') }}">Login</a>
            <a class="hyper" href="{{ url_for('users.sign_up')}}">Sign up</a>
            
        {% endif %}
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == "error" %}
            <div class="alert alert-danger" id="alert">
                <p class=flash-message>{{ message }}</p>
            </div>

            {% else %}
            <div class="alert alert-success" id="alert">
                <p class=flash-message>{{ message }}</p>
            </div>
           {% endif %}     
        {% endfor %}  
    {% endif %}
    {% endwith %}

    <script type="text/javascript">
        setTimeout(function() {
            document.getElementById("alert").style.display = 'none';
        }, 5000)
    </script>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

myshare/templates/create_post.html
{% extends "base.html" %} 

{% block title %}{% endblock%}

{% block content%}
<h2>{{ legend }}</h2>
<div>
    <form class="my-form post-form" method="POST">
     <div class="form-group">
        {{ form.title.label }}
        {{ form.title(type="text", id="title") }}
    </div>
    <div class="form-group">
        {{ form.link.label }}
        {{ form.link(type="text") }}
    </div>
    <div class="form-group">
        {{ form.submit(type="submit", class="button") }}
    </div>
    <div>
        <input type="hidden" name="next" value="{{ request.args.get('next') }}" />
    </div>
    </form>
</div>
{% endblock %}

myshare/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock%}

{% block content%}
<h2>Hello, {{ current_user.username }}</h2>

{% for link in links.items %}
<div class="con-div">

    <!-- Below is for the profile image -->
    <!-- <div class="home-profile-pic"> -->
    <!-- <img id="post-img" src="{{ url_for('static', filename='profile_pics/' + link.author.image_file) }}"> -->
    <!-- </div> -->

    <a class="text" href={{ link.content }}>{{ link.title.title() }}</a>
    <p>Posted by <a class="text" href="{{ url_for('users.user_posts', username=link.author.username) }}">{{ link.author.username.title() }}</a> on {{ link.date_posted.strftime("%Y-%m-%d") }}</p>
    {% if link.author == current_user %}
            <div>

                <form method="POST">
                    <button class="update-button" formaction="{{ url_for('link_posts.update_post', post_id=link.id) }}">Update</button>
                    <button class="delete-button" formaction="{{ url_for('link_posts.delete_post', post_id=link.id) }}" onclick="return myConfirm()" type="submit" name="actiondelete" value="1">Delete</button>
                </form>

            

            <script>
                function myConfirm() {
                var user_name = "{{ current_user.username }}"
                var result = confirm(user_name + "\nDo you want to delete post?");
                if (result==true) {
                return true;
                } 
                else {
                return false;
                }
                }
            </script>             


                
            </div>
        {% endif %}
    
</div>
<br>
{% endfor %}

{% for page_num in links.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if links.page == page_num %}
        <div class="paginate">
            <a href="{{ url_for('main.home', page=page_num) }}" class="active">{{ page_num }}</a>
        </div>
        {% else %}
        <div class="paginate">
            <a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        </div>
        {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}

{% endblock %}

myshare/templates/login.html
{% extends "base.html" %}


{% block content %}

<form class="my-form" method="post">
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email }}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password }}
    </div>
    <div class="form-group">
        {{ form.submit(type="submit", class="button") }}
    </div>
    <a href="{{ url_for('users.reset_request')}}">Forgot password?</a>
</form>

{% endblock %}

myshare/templates/reset_request.html
{% extends "base.html" %}


{% block content %}
<h2>Reset password:</h2>

<form class="my-form" method="post">
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email }}
    </div>
    <div class="form-group">
        {{ form.submit(type="submit", class="reset-button") }}
    </div>
</form>

{% endblock %}

myshare/templates/reset_token.html
{% extends "base.html" %}


{% block content %}
<h1>Reset password</h1>

<form class="my-form" method="post">
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password }}
    </div>
    <div class="form-group">
        {{ form.confirm_password.label }}
        {{ form.confirm_password }}
    </div>
    <div class="form-group">
        {{ form.submit(type="submit", class="button") }}
    </div>
</form>

{% endblock %}

myshare/templates/sign-up.html
{% extends "base.html" %}


{% block content %}

<!-- <fieldset> -->
<form class="my-form" method="post">
    <div class="form-group">
        {{ form.username.label }}
        {{ form.username }}
    </div>
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email }}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password }}
    </div>
    <div class="form-group">
        {{ form.confirm_password.label }}
        {{ form.confirm_password }}
    </div>
    <div class="form-group">
        {{ form.submit(type="submit", class="button") }}
    </div>
</form>
<!-- </fieldset> -->

{% endblock %}

myshare/templates/user_posts.html
{% extends "base.html" %} {% block title %}Home{% endblock%}

{% block content%}
<h2>Posts  by {{ user.username }} ({{ links.total }})</h2>

{% for link in links.items %}
<div class="con-div">

    <!-- Below is for the profile image -->
    <!-- <div class="home-profile-pic"> -->
    <!-- <img id="post-img" src="{{ url_for('static', filename='profile_pics/' + link.author.image_file) }}"> -->
    <!-- </div> -->

    <a class="text" href={{ link.content }}>{{ link.title.title() }}</a>
    <p>Posted by <a class="text" href="{{ url_for('users.user_posts', username=link.author.username) }}">{{ link.author.username.title() }}</a> on {{ link.date_posted.strftime("%Y-%m-%d") }}</p>
    {% if link.author == current_user %}
            <div>

                <form method="POST">
                    <button class="update-button" formaction="{{ url_for('link_posts.update_post', post_id=link.id) }}">Update</button>
                    <button class="delete-button" formaction="{{ url_for('link_posts.delete_post', post_id=link.id) }}" onclick="return myConfirm();" type="submit" name="actiondelete" value="1">Delete</button>
                </form>

            

            <script>
                function myConfirm() {
                var user_name = "{{ current_user.username }}"
                var result = confirm(user_name + "\nDo you want to delete post?");
                if (result==true) {
                return true;
                } else {
                return false;
                }
                }
            </script>             


                
            </div>
        {% endif %}
    
</div>
<br>
{% endfor %}

{% for page_num in links.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if links.page == page_num %}
        <div class="paginate">
            <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="active">{{ page_num }}</a>
        </div>
        {% else %}
        <div class="paginate">
            <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        </div>
        {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}

{% endblock %}